public enum EventsEnum
{
    TURNSTART,
    HEALBEFORETAKE,
    HEALAFTERTAKE,
    DAMAGEBEFORETAKE,
    DAMAGEAFTERTAKE,
    RESOURCEBEFORETAKE,
    RESOURCEAFTERTAKE,
    OVERTIMEBEFORETAKE,
    OVERTIMEAFTERTAKE,
    ABILITYBEFOREUSE,
    ABILITYAFTERUSE,
    POSITIONBEFORECHANGE,
    POSITIONAFTERCHANGE,
    TURNEND,
}
